@PortfolioLab.Api_HostAddress = http://localhost:5175

POST {{PortfolioLab.Api_HostAddress}}/api/positions/calculate
Content-Type: application/json

[
  {
    "instrumentId": "AAPL",
    "side": "Buy",
    "quantity": 100,
    "unitPrice": 150,
    "executedAt": "2026-08-19T10:00:00Z"
  },
  {
    "instrumentId": "AAPL",
    "side": "Sell",
    "quantity": 40,
    "unitPrice": 180,
    "executedAt": "2026-08-19T11:00:00Z"
  }
]

### Negative quantity - should return 400
POST {{PortfolioLab.Api_HostAddress}}/api/positions/calculate
Content-Type: application/json

[
  {
    "instrumentId": "AAPL",
    "side": "Buy",
    "quantity": -50,
    "unitPrice": 150,
    "executedAt": "2026-08-19T10:00:00Z"
  }
]

### Oversell - should return 400
POST {{PortfolioLab.Api_HostAddress}}/api/positions/calculate
Content-Type: application/json

[
  {
    "instrumentId": "AAPL",
    "side": "Buy",
    "quantity": 100,
    "unitPrice": 150,
    "executedAt": "2026-08-19T10:00:00Z"
  },
  {
    "instrumentId": "AAPL",
    "side": "Sell",
    "quantity": 150,
    "unitPrice": 180,
    "executedAt": "2026-08-19T11:00:00Z"
  }
]